### ISSUE TITLE
Please stop this project. Just stop

### ISSUE THREAD

**Issue by mrpackethead** [cdklabs/cdk-enterprise-iac#142]
### General Issue

This is a massive backwards step

### The Question

Not only is it a massive time sink, but its not even  practical.

Any business large enough to segregate duties to the level this code addresses, wont be able to use this code. Governance, Network and Security functions in enterprises very rarely have the skills to write code or a deep understanding of AWS. Enterprise processes dont align either, as you will almost certainly have Change Control, CAB, ITIL and manual governance/approval in the food chain.

This is the kind of thing that some well meaning security consultant will try to roll in, and will just drive good folks to organisations that let them actualy work

The best thing the topic specialists could do is provide advice on best practice/governance. They would be better equipped to do a PR of a manifest file of sec group rules than try and write code.
Concerns about dev access to accounts or services should be addressed by the CICD tooling. Give it the rights, block execution via branching and PR's. Then you remove the need for security/networking teams to have escalated privileges as well.
That strategy wont help you sell consulting or ensure your relevance in a large enterprise though.

What we have here is a technical answer to resolving a human problem, when what is really needed is a human problem to resolve a human problem. 

### cdk-enterprise-iac version

N/A

### Language

Typescript

**Comment by maafk** [comment]
Thanks for opening @mrpackethead 

This project includes many Constructs/Aspects aimed at making it easier to write infrastructure as code in CDK within the context of restrictive enterprise environments.

Not all of these will be right for every enterprise and use cases, and we welcome all to open issues/PRs to help address specific use cases.

While true that many Constructs/Aspects in this project are technical solutions to constraints imposed by the enterprise (human problems), enterprise constraints tend to take much longer to resolve. Meanwhile builders are expected to deliver results. In light of this reality, this project aims to increase velocity for enterprise developers when writing their AWS infrastructure as code using CDK while these issues are sorted out.

Many builders are using this project, saving countless hours of development time in seamlessly handling enterprise frictions, so we will keep this project going as long as builders are finding it valuable.

Thanks!
