### ISSUE TITLE
bug: ECS Autoscaling IAM Default role permissions insufficient

### ISSUE THREAD

**Issue by duncanBotti** [cdklabs/cdk-enterprise-iac#202]
### What is the problem?

After deploying the ISO autoscaler lambda invokations return this error: 

```
ClientError: An error occurred (AccessDenied) when calling the DescribeAlarms operation 
```

### Reproduction Steps

1. Deploy ISO autoscaler
2. Monitor Lambda Function Logs 

### What did you expect to happen?

Logs to indicate scaling or no scaling action was taken, cluster to scale. 

### What actually happened?

Lambda failed with errors, no scaling action taken 

### cdk-enterprise-iac version

latest 

### Language

Typescript

**Comment by duncanBotti** [comment]
Assign to me please

**Comment by maafk** [comment]
Erroring when user passes a composite alarm.

According to [docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/permissions-reference-cw.html)

> cloudwatch:DescribeAlarms
>
> Required to retrieve information about alarms.
>
> To retrieve information about composite alarms, your cloudwatch:DescribeAlarms permission must have a * scope. You can't return information about composite alarms if your cloudwatch:DescribeAlarms permission has a narrower scope.

**Comment by maafk** [comment]
Completed in #203
