### ISSUE TITLE
feat: Autoscaling mechanism for regions without ECS task autoscaling

### ISSUE THREAD

**Issue by maafk** [cdklabs/cdk-enterprise-iac#22]
### Description

In some AWS regions, [ECS service autoscaling](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-auto-scaling.html) is not supported.

As a result, ECS cluster deployments have a fixed number of tasks requiring manual updating

### Use Case

As an ECS service gets increased utilization and hits resource limits such as CPU and memory, additional tasks can't be automatically started to handle the load without manual intervention.

Conversely, as utilization decreases and fewer ECS tasks are needed to handle the workload, tasks aren't removed from the ECS service, resulting in over provisioning of resources and added costs.

### Proposed Solution

A construct to track Cloudwatch Metrics for an ECS service, and set the desired task count for the service based on those metrics.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by duncanBotti** [comment]
Feel free to assign me.
